const actionTypes = {
	FETCH_CURIOSITY: 'FETCH_CURIOSITY',
	FETCH_OPPORTUNITY: 'FETCH_OPPORTUNITY',
	FETCH_SPIRIT: 'FETCH_SPIRIT',
	SLIDE_LEFT: 'SLIDE_LEFT',
	SLIDE_RIGHT: 'SLIDE_RIGHT'
};

export default actionTypes;
